const plantas = [
    {
      id: 1,
      nombre: "Aloe Vera",
      imagen: "https://example.com/aloe-vera.jpg",
      descripcion: "Planta suculenta conocida por sus propiedades medicinales.",
      precio: 9.99,
      stock: 25,
    },
    {
      id: 2,
      nombre: "Cactus de Navidad",
      imagen: "https://example.com/cactus-navidad.jpg",
      descripcion: "Planta colgante que florece en invierno con colores vibrantes.",
      precio: 12.49,
      stock: 15,
    },
    {
      id: 3,
      nombre: "Monstera Deliciosa",
      imagen: "https://example.com/monstera.jpg",
      descripcion: "Planta tropical con hojas grandes y perforadas.",
      precio: 19.99,
      stock: 10,
    },
    {
      id: 4,
      nombre: "Pothos Dorado",
      imagen: "https://example.com/pothos-dorado.jpg",
      descripcion: "Planta trepadora fácil de cuidar, ideal para interiores.",
      precio: 7.99,
      stock: 30,
    },
    {
      id: 5,
      nombre: "Ficus Lyrata",
      imagen: "https://example.com/ficus-lyrata.jpg",
      descripcion: "Planta de interior con hojas grandes en forma de violín.",
      precio: 24.99,
      stock: 8,
    },
    {
      id: 6,
      nombre: "Helecho de Boston",
      imagen: "https://example.com/helecho.jpg",
      descripcion: "Planta colgante con frondas largas y verdes.",
      precio: 14.49,
      stock: 18,
    },
    {
      id: 7,
      nombre: "Lavanda",
      imagen: "https://example.com/lavanda.jpg",
      descripcion: "Planta aromática conocida por su efecto relajante.",
      precio: 9.49,
      stock: 20,
    },
    {
      id: 8,
      nombre: "Bambú de la Suerte",
      imagen: "https://example.com/bambu.jpg",
      descripcion: "Planta de agua considerada símbolo de buena fortuna.",
      precio: 5.99,
      stock: 40,
    },
    {
      id: 9,
      nombre: "Sansevieria",
      imagen: "https://example.com/sansevieria.jpg",
      descripcion: "Planta resistente conocida como 'Lengua de Suegra'.",
      precio: 11.99,
      stock: 22,
    },
    {
      id: 10,
      nombre: "Palma Areca",
      imagen: "https://example.com/palma-areca.jpg",
      descripcion: "Palma de interior que aporta un toque tropical.",
      precio: 29.99,
      stock: 12,
    },
    {
      id: 11,
      nombre: "Hiedra Inglesa",
      imagen: "https://example.com/hiedra.jpg",
      descripcion: "Planta trepadora ideal para decoración de paredes.",
      precio: 6.99,
      stock: 28,
    },
    {
      id: 12,
      nombre: "Calathea Orbifolia",
      imagen: "https://example.com/calathea.jpg",
      descripcion: "Planta de interior con hojas grandes y rayadas.",
      precio: 16.49,
      stock: 14,
    },
    {
      id: 13,
      nombre: "Dracaena Marginata",
      imagen: "https://example.com/dracaena.jpg",
      descripcion: "Planta alta y estilizada con hojas largas.",
      precio: 22.99,
      stock: 9,
    },
    {
      id: 14,
      nombre: "Jade",
      imagen: "https://example.com/jade.jpg",
      descripcion: "Planta suculenta conocida por su longevidad.",
      precio: 8.99,
      stock: 35,
    },
    {
      id: 15,
      nombre: "Begonia Rex",
      imagen: "https://example.com/begonia.jpg",
      descripcion: "Planta con hojas decorativas y colores vibrantes.",
      precio: 13.49,
      stock: 16,
    },
    {
      id: 16,
      nombre: "Planta Araña",
      imagen: "https://example.com/planta-arana.jpg",
      descripcion: "Planta de interior que purifica el aire.",
      precio: 7.49,
      stock: 25,
    },
    {
      id: 17,
      nombre: "Orquídea Phalaenopsis",
      imagen: "https://example.com/orquidea.jpg",
      descripcion: "Planta elegante con flores de colores variados.",
      precio: 18.99,
      stock: 12,
    },
    {
      id: 18,
      nombre: "Cactus Echinopsis",
      imagen: "https://example.com/echinopsis.jpg",
      descripcion: "Cactus que florece con flores grandes y coloridas.",
      precio: 10.99,
      stock: 20,
    },
    {
      id: 19,
      nombre: "Peperomia",
      imagen: "https://example.com/peperomia.jpg",
      descripcion: "Planta compacta con hojas variadas en forma y color.",
      precio: 9.49,
      stock: 18,
    },
    {
      id: 20,
      nombre: "Zamioculcas",
      imagen: "https://example.com/zamioculcas.jpg",
      descripcion: "Planta resistente, perfecta para principiantes.",
      precio: 15.99,
      stock: 21,
    },
    {
      id: 21,
      nombre: "Eucalipto",
      imagen: "https://example.com/eucalipto.jpg",
      descripcion: "Planta aromática con un fresco aroma característico.",
      precio: 13.99,
      stock: 15,
    },
    {
      id: 22,
      nombre: "Romero",
      imagen: "https://example.com/romero.jpg",
      descripcion: "Planta aromática ideal para cocinar.",
      precio: 6.49,
      stock: 30,
    },
    {
      id: 23,
      nombre: "Cinta o Lazo de Amor",
      imagen: "https://example.com/cinta.jpg",
      descripcion: "Planta fácil de cuidar que crece rápidamente.",
      precio: 8.49,
      stock: 27,
    },
    {
      id: 24,
      nombre: "Fitonia",
      imagen: "https://example.com/fitonia.jpg",
      descripcion: "Planta de interior con hojas pequeñas y nervadas.",
      precio: 12.99,
      stock: 17,
    }
  ];
  